package androidx.viewpager2.integration.testapp.tag

const val Card_TAG = "Card class[app]"
const val CardView_TAG = "CardView class[app]"
const val CardViewAdapter_TAG = "CardViewAdapter class[app]"
const val CardViewHolder_TAG = "CardViewHolder class[app]"
const val BaseCardActivity_TAG = "BaseCardActivity class[app]"
const val BrowseActivity_TAG = "BrowseActivity class[app]"
const val CardFragmentActivity_TAG = "CardFragmentActivity class[app]"
const val CardFragmentActivity_CardFragment_TAG = "CardFragmentActivity.CardFragment class[app]"
const val CardViewActivity_TAG = "CardViewActivity class[app]"
const val CardViewTabLayoutActivity_TAG = "CardViewTabLayoutActivity class[app]"
const val FakeDragActivity_TAG = "FakeDragActivity class[app]"
const val MutableCollectionBaseActivity_TAG = "MutableCollectionBaseActivity class[app]"
const val ItemsViewModel_TAG = "ItemsViewModel class[app]"
const val MutableCollectionFragmentActivity_TAG = "MutableCollectionFragmentActivity class[app]"
const val PageFragment_TAG = "PageFragment class[app]"
const val MutableCollectionViewActivity_TAG = "MutableCollectionViewActivity class[app]"
const val PageViewHolder_TAG = "PageViewHolder class[app]"
const val ClickRegistry_TAG = "ClickRegistry class[app]"
const val NestedScrollableHost_TAG = "NestedScrollableHost class[app]"
const val OrientationController_TAG = "OrientationController class[app]"
const val PageTransformerActivity_TAG = "PageTransformerActivity class[app]"
const val PageTransformerController_TAG = "PageTransformerController class[app]"
const val ParallelNestedScrollingActivity_TAG = "ParallelNestedScrollingActivity class[app]"
const val ParallelNestedScrollingActivity_VpAdapter_TAG =
    "ParallelNestedScrollingActivity.VpAdapter class[app]"
const val VpAdapter_ViewHolder_TAG = "VpAdapter.ViewHolder class[app]"
const val ParallelNestedScrollingActivity_RvAdapter_TAG =
    "ParallelNestedScrollingActivity.RvAdapter class[app]"
const val RvAdapter_ViewHolder_TAG = "RvAdapter.ViewHolder class[app]"
const val PreviewPagesActivity_TAG = "PreviewPagesActivity class[app]"
const val PreviewPagesActivity_ViewHolder_TAG = "PreviewPagesActivity.ViewHolder class[app]"
const val PreviewPagesActivity_Adapter_TAG = "PreviewPagesActivity.Adapter class[app]"
const val UserInputController_TAG = "UserInputController class[app]"
